### ISSUE TITLE
date mask for order of month/day is ignored if day and month are both <=12 

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#89] opened 2018-12-19 15:12 UTC
See the updated datatypesdemo.bbj. The date in the timestamp and the date are now on the same day for each row. The date mask is European with day/month/year. The date/month portion is reversed for those rows where day and month are below 13:

![image](https://user-images.githubusercontent.com/4833070/50228675-d1289e80-03a8-11e9-94c7-a8f43794eb7e.png)

**Comment by hyyan** [comment] 2018-12-24 15:35
@StephanWald It seems, this is the fault of basis components  somehow, in the demo the timestamp is defined as `1979-08-03 12:22:13`  but passed to the client as `2013-10-23T23:22:00.0+01:00` ,  parsing the first form in the client will result in `08.03.1979 12:22:13` and the second one will result in `03.08.1979 12:22:13`.

We are **NOT** using momentjs to parse dates , but pasring the second form in momentjs will give the same reuslts.  Maybe let David check the format coming from BBj , it does not seem to be correct

**Comment by StephanWald** [comment] 2018-12-24 15:51
Below is the full data, which is correct:

Each row has the same day in the date and the timestamp:
Two rows have the 3. August 1979 and two rows have the 23. October 2013.

They are correctly reflected below in the JSon that's passed to the grid, and in the screenshot of @hyyan you see that the record #2 is the 1979 date, with the TIMESTAMP field (only halfway visible at the lower border) also showing as 1979-08-03. So the JSON is correct, but the grid shows the 1979 date incorrectly but the 1979 timestamp correctly.



[{
		"INTEGER": 1,
		"ICON": "ID_1",
		"IMAGELIST": "0",
		"DOUBLE": 1234.0,
		"BOOLEAN 1": false,
		"BOOLEAN 2": false,
		"BOOLEAN 3": false,
		"DATE": "1979-08-03",
		"TIMESTAMP": "1979-08-03T12:22:13.0+01:00",
		"meta": {
			"INTEGER": {
				"ColumnType": "4"
			},
			"ICON": {
				"ColumnType": "12"
			},
			"IMAGELIST": {
				"ColumnType": "12"
			},
			"DOUBLE": {
				"ColumnType": "8"
			},
			"BOOLEAN 1": {
				"ColumnType": "16"
			},
			"BOOLEAN 2": {
				"ColumnType": "16"
			},
			"BOOLEAN 3": {
				"ColumnType": "16"
			},
			"DATE": {
				"ColumnType": "91"
			},
			"TIMESTAMP": {
				"ColumnType": "93"
			},
			"STRING": {
				"ColumnType": "12"
			}
		}
	}, {
		"INTEGER": 2,
		"ICON": "ID_2",
		"IMAGELIST": "1",
		"DOUBLE": -2468.0,
		"BOOLEAN 1": false,
		"BOOLEAN 2": false,
		"BOOLEAN 3": false,
		"DATE": "2013-10-23",
		"TIMESTAMP": "2013-10-23T23:22:00.0+01:00"
	}, {
		"INTEGER": 3,
		"ICON": "ID_3",
		"IMAGELIST": "2",
		"DOUBLE": 7404.0,
		"BOOLEAN 1": true,
		"BOOLEAN 2": true,
		"BOOLEAN 3": true,
		"DATE": "1979-08-03",
		"TIMESTAMP": "1979-08-03T12:22:13.0+01:00"
	}, {
		"INTEGER": 4,
		"ICON": "ID_4",
		"IMAGELIST": "3",
		"DOUBLE": -29616.0,
		"BOOLEAN 1": false,
		"BOOLEAN 2": false,
		"BOOLEAN 3": false,
		"DATE": "2013-10-23",
		"TIMESTAMP": "2013-10-23T23:22:00.0+01:00"
	}, {
		"STRING": "ROW NUMBER 5"
	}
]

**Comment by hyyan** [comment] 2018-12-24 16:41
@StephanWald  I see the issue now, this one is coming from [Datejs](https://github.com/datejs/Datejs)
it needs a deeper look

**Comment by hyyan** [comment] 2018-12-24 16:45
@StephanWald 
is bbj language set to "de_DE" in your environment?

**Comment by StephanWald** [comment] 2018-12-24 16:55
yes it is. But if it weren't shouldn't still all dates be represented the same way?

**Comment by hyyan** [comment] 2018-12-24 16:58
@StephanWald 
Not really , parsing dates is language sensitive.

**Comment by hyyan** [comment] 2019-01-13 11:39
@StephanWald 
After digging in this one, I found that the current `Datejs` behavior is **correct**, the problem is coming from the dates generated by basis components.
In general date parsing is language-dependent

**Examples:**

| Date/DateTime       | Format                  | Language | Result              |
|---------------------|-------------------------|----------|---------------------|
| 1979-08-03          | %Dz.%Mz.%Yd             | en       | 03-08-1979          |
| 2013-10-23 23:22:00 | %Dz.%Mz.%Yl %Hz:%mz:%sz | en       | 03-08-1979 23:22:00 |
| 1979-08-03          | %Dz.%Mz.%Yd             | de       | 08-03-1979          |
| 2013-10-23 23:22:00 | %Dz.%Mz.%Yl %Hz:%mz:%sz | de       | 08-03-1979 23:22:00 |

In our demo, if you set the language to `en-US` then you will see correct results, if you set the language to `de` you will see an incorrect result for the date and correct result for the DateTime. The reason for this is that basis component is formatting the DateTime in a valid ISO 8601 format but not dates.
ISO 8601 format is **language-independent** . To use the ISO 8601 format, you must specify each element in the format. This includes the T, the colons (:), the + or - , and the periods (.) . so the `"DATE":"1979-08-03",` in  json should be `"DATE":"1979-08-03T00:00:00",` so Javascript can understand that we do not need to parse/format the date depening on the passed langauge

**Comment by hyyan** [comment] 2019-01-16 06:07
@StephanWald  can we consider this closed?

**Comment by hyyan** [comment] 2019-02-25 17:58
@StephanWald  closing as the issue is resolved and the solution is pushed in the master branch.
see #91

**Closed by hyyan** 2019-02-25 17:58 UTC
Labels: Wontfix
