### ISSUE TITLE
[Bug] Grid does not correctly startCellEditing im DWC/BUI

### ISSUE THREAD

**Issue by TimonGeisbauer** [BBj-Plugins/BBjGridExWidget#246] opened 2022-09-30 08:33 UTC
In this Sample you have a pinned Row where you can start editing and tab trough all the columns.
Once you reached the end the code in the onEditingCompleted i set the first column visible again and then
start the CellEditing again. The cell editing works fine in guy but does not work in DWC/BUI.
The Cell gets the Styling as if editable but if you try to type nothing happens and also there is no cursor visible in the cell.
Adding a grid!.focus() as it is in this sample does not help in DWC/BUI and is not necessary for it to work in the GUI.

```java
use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget
use com.basiscomponents.db.ResultSet
use com.basiscomponents.db.DataRow

use ::BBjGridExWidget/GxColumns.bbj::GxColumn
use ::BBjGridExWidget/GxClientEvents.bbj::GxClientEventsCell

sysgui! = BBjAPI().openSysGui("X0")
wnd! = sysgui!.addWindow(0,0,800,600,"GridExSample")

wnd!.setCallback(BBjAPI.ON_CLOSE,"byebye")
grid! = new BBjGridExWidget(wnd!,9876,0,0,wnd!.getWidth(),wnd!.getHeight())
grid!.setCallback(grid!.ON_GRID_CELL_EDITING_STOPPED(),"onEditingCompleted")

rem grid!.getOptions().setStopEditingWhenGridLosesFocus(1)

c! = new GxColumn("1_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("2_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("3_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("4_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("5_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("6_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("7_")
c!.setEditable(1)
grid!.addColumn(c!)
c! = new GxColumn("8_")
c!.setEditable(1)
grid!.addColumn(c!)

dr! = new DataRow()
dr!.setFieldValue("__INDEX__","0123456789")
for i = 1 to 8 
dr!.setFieldValue(str(i) + "_","")
next i

rs! = new ResultSet()
rs!.add(dr!)
grid!.setPinnedBottomRows(rs!)

data! = new ResultSet()
entry! = new DataRow()
entry!.setFieldValue("1_","test")
entry!.setFieldValue("2_","test")
entry!.setFieldValue("3_","test")
entry!.setFieldValue("4_","test")
entry!.setFieldValue("5_","test")
entry!.setFieldValue("6_","test")
entry!.setFieldValue("7_","test")
entry!.setFieldValue("8_","test")
data!.add(entry!)

grid!.setData(data!)

process_events

onEditingCompleted:
ev! = BBjAPI().getLastEvent()
declare auto GxClientEventsCell cell!
declare DataRow dr!

declare BBjString cname!

cell! = ev!.getObject()
cname! = cell!.getColumn().getName()

if (cname! = "8_") then 
    grid!.setVisibleColumn("1_")
    grid!.setStartCellEditing(0,"1_",-1,"",grid!.GRID_FLOATING_BOTTOM())
    grid!.focus(0,"1_",grid!.GRID_FLOATING_BOTTOM())
endif

return
```

**Comment by hyyan** [comment] 2022-10-25 09:36
Duplicate of #245

**Closed by hyyan** 2022-10-25 09:36 UTC
Labels: Type: Duplicate
